### ISSUE TITLE
License Information

### ISSUE THREAD

**Issue by ChristianOConnor** [surg0r/lamport#1]
Hey Surg0r!
Awesome work! Love your cryptography projects and I love QRL! Great coin! Anyway I really like your python implementation of Lamport signatures. What is the license for using the code? MIT, Apache, etc...?

Christian

**Comment by surg0r** [comment]
Thanks Christian! It's free to use without attribution. I can add a license
if you wish.

Kindest regards,

Peter

**Comment by ChristianOConnor** [comment]
Oh perfect! Thanks Peter! That's great to know, thank you for the information. As far as adding a license is concerned it's totally up to you but yeah I would love to see a license added if possible and if it's not too much trouble.

Again, I love the code and I love the project!

Christian

**Comment by surg0r** [comment]
MIT license added
